#! /bin/bash
### BEGIN INIT INFO
# Provides:          graphite_workew
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4
# Default-Stop:      0 1 5 6
# Short-Description: Graphite Worker
# Description:       Graphite Worker for ModGearman. Feeds Nagios/Icinga Performancedata
#                    into Graphite/Carbon
### END INIT INFO

PATH="/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/bin:/usr/local/sbin"

. /lib/lsb/init-functions

NAME="graphite_worker"
DAEMON=`which graphite_worker`
USER="nobody"
GROUP="nogroup"
CONFIG="/etc/graphite_worker/worker.json"
PIDFILE="/var/run/${NAME}.pid"

test -x ${DAEMON} || exit 5

case $1 in
        start)
                log_daemon_msg "Starting" "${NAME}"
                start-stop-daemon --start --quiet --pidfile ${PIDFILE} --startas ${DAEMON} -- -c ${CONFIG} -u ${USER} -g ${GROUP} -p ${PIDFILE}
                status=$?
                log_end_msg $status
                ;;
        stop)
                log_daemon_msg "Stopping" "${NAME}"
                start-stop-daemon --stop --quiet --pidfile ${PIDFILE}
                RET=$?
                log_end_msg ${RET}
                rm -f ${PIDFILE}
                exit ${RET}
                ;;
        restart|force-reload)
                $0 stop && sleep 2 && $0 start
                ;;
        try-restart)
                if $0 status >/dev/null; then
                        $0 restart
                else
                        exit 0
                fi
                ;;
        reload)
                exit 3
                ;;
        status)
                status_of_proc -p ${PIDFILE} ${DAEMON} "${NAME} daemon"
                ;;
        *)
                echo "Usage: $0 {start|stop|restart|try-restart|force-reload|status}"
                exit 2
                ;;
esac
